Add AC_USE_SYSTEM_EXTENSIONS to expose non-standard extensions
Required on Solaris to expose definitions in system headers that
are not defined in the XPG standards now that xtrans 1.3 defines
_XOPEN_SOURCE to 600 on Solaris.

Fixes build failures:
In file included from /usr/include/rpc/rpcb_clnt.h:34:0,
                 from /usr/include/rpc/rpc.h:49,
                 from xhost.c:98:
/usr/include/rpc/rpcb_prot.h:159:3: error: unknown type name ‘u_int’
/usr/include/rpc/rpcb_prot.h:195:3: error: unknown type name ‘u_int’
/usr/include/rpc/rpcb_prot.h:223:2: error: unknown type name ‘u_int’
/usr/include/rpc/rpcb_prot.h:476:1: error: unknown type name ‘u_int’
/usr/include/rpc/rpcb_prot.h:489:1: error: unknown type name ‘u_int’

xhost.c: In function ‘change_host’:
xhost.c:554:11: error: ‘INET6_ADDRSTRLEN’ undeclared (first use in this function)
xhost.c:554:11: note: each undeclared identifier is reported only once for each function it appears in

xhost.c: In function ‘get_hostname’:
xhost.c:665:23: error: ‘NI_MAXHOST’ undeclared (first use in this function)

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Daniel Stone <daniel@fooishbar.org>